# TODO: Add Hackage fields
name: shrtn
version: 0.1.0.0

# TODO: turn on -Werror after some development
ghc-options: -Wall -O2

dependencies:
  - acid-state < 0.15
  - aeson < 1.2
  - async < 2.2
  - base >= 4.7 && < 5
  - http-types < 0.10
  - mtl < 2.3
  - servant-server < 0.12
  - safecopy < 0.15
  - text < 1.3
  - unordered-containers < 0.3
  - wai < 3.3
  - warp < 3.3

executables:
  shrtn:
    source-dirs: src
    main: Main.hs
